changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: New Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Maintenance
      labels:
        - chore
        - docs
        - refactor
        - dependencies
        - ci
    - title: Other Changes
      labels:
        - "*"
